import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createRequire} from 'node:module';
const req=createRequire(import.meta.url);const ts=req('typescript');const dir=mkdtempSync(join(tmpdir(),'frescapp-avisos-'));
after(()=>rmSync(dir,{recursive:true,force:true}));
const compile=(name,text)=>writeFileSync(join(dir,name+'.js'),ts.transpileModule(text,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText);
for(const f of ['fechas','avisosModelo'])compile(f,readFileSync(new URL('../services/'+f+'.ts',import.meta.url),'utf8'));
const {planificarAvisos,preferenciasValidas,AVISOS_INICIALES}=req(join(dir,'avisosModelo.js'));
process.env.TZ='America/Santiago';
const p={...AVISOS_INICIALES,activo:true};const now=new Date(2026,9,4,12);const producto=(v,cantidad=1)=>({vencimiento:v,cantidad});
test('apagado no programa y preferencias tienen límites',()=>{assert.deepEqual(planificarAvisos([producto('05/10/2026')],AVISOS_INICIALES,now),[]);for(const cambio of [{hora:24},{minuto:60},{hora:1.5},{anticipacion:2},{activo:'sí'}])assert.throws(()=>preferenciasValidas({...p,...cambio}));});
test('agrupa 200 lotes en un resumen diario',()=>{const plan=planificarAvisos(Array.from({length:200},()=>producto('04/10/2026')),p,now);assert.equal(plan.length,1);assert.equal(plan[0].registros,200);});
test('excluye vencidos, fecha inválida, sin fecha y stock cero',()=>assert.deepEqual(planificarAvisos(['03/10/2026','31/02/2026','Sin fecha'].map(v=>producto(v)).concat(producto('04/10/2026',0)),p,now),[]));
test('no programa horas pasadas y limita horizonte a siete días',()=>{const plan=planificarAvisos([producto('11/10/2026')],{...p,anticipacion:7},new Date(2026,9,4,20));assert.equal(plan.length,6);assert(plan.every(a=>a.fecha>new Date(2026,9,4,20)));});
test('fecha mes/año usa el último día del mes',()=>{const plan=planificarAvisos([producto('10/2026')],p,new Date(2026,9,30,12));assert.equal(plan.length,2);});
test('el cambio de horario de Chile conserva días civiles',()=>{const plan=planificarAvisos([producto('07/09/2026')],p,new Date(2026,8,5,12));assert.deepEqual(plan.map(a=>a.fecha.getDate()),[5,6,7]);assert(plan.every(a=>a.fecha.getHours()===19));});
const storage=new Map();globalThis.__avisosFake={auth:{currentUser:{uid:'A'}},storage,items:[],permitido:true,limpiezas:0,gate:null,observador:null,pedidos:0};
compile('auth','export const auth=globalThis.__avisosFake.auth;');
compile('fakeStorage','const x=globalThis.__avisosFake;export default {getItem:async k=>x.storage.get(k)||null,setItem:async(k,v)=>{x.storage.set(k,v)}};');
compile('fakeAuth','export function onAuthStateChanged(auth,f){globalThis.__avisosFake.observador=f;return ()=>{};}');
compile('avisosDispositivo',`const x=globalThis.__avisosFake;export const disponible=true;export const limpiar=async()=>{x.limpiezas++;x.items=[];};export const permiso=async pedir=>{if(pedir)x.pedidos++;return x.permitido;};export const cancelar=async id=>{x.items=x.items.filter(a=>a.id!==id)};export const programar=async(uid,a)=>{if(x.gate)await x.gate;const id=String(Math.random());x.items.push({id,uid,a});return id};`);
compile('avisos',readFileSync(new URL('../services/avisos.ts',import.meta.url),'utf8').replace("'@react-native-async-storage/async-storage'","'./fakeStorage'").replace("'firebase/auth'","'./fakeAuth'"));
const s=req(join(dir,'avisos.js'));const x=globalThis.__avisosFake;
const futuro=new Date();futuro.setDate(futuro.getDate()+2);const fecha=`${futuro.getDate()}/${futuro.getMonth()+1}/${futuro.getFullYear()}`;const datos=[producto(fecha)];
test('preferencias aisladas y permiso solicitado solo al activar',async()=>{await s.guardarPreferenciasAvisos(p);assert.equal(x.pedidos,1);assert.equal((await s.leerPreferenciasAvisos('B')).activo,false);assert.equal((await s.leerPreferenciasAvisos('A')).activo,true);});
test('plan idéntico no duplica ni vuelve a pedir permiso',async()=>{await s.actualizarAvisos('A',datos,p);const n=x.items.length;const l=x.limpiezas;await s.actualizarAvisos('A',datos,p);assert(n>0);assert.equal(x.items.length,n);assert.equal(x.limpiezas,l);assert.equal(x.pedidos,1);});
test('eliminar stock cancela los resúmenes obsoletos',async()=>{await s.actualizarAvisos('A',[],p);assert.equal(x.items.length,0);});
test('denegar permiso no activa preferencias nuevas',async()=>{x.auth.currentUser={uid:'B'};x.permitido=false;await assert.rejects(s.guardarPreferenciasAvisos(p),/Permiso/);assert.equal((await s.leerPreferenciasAvisos('B')).activo,false);x.permitido=true;x.auth.currentUser={uid:'A'};});
test('cambio de cuenta durante programación cancela el aviso en vuelo',async()=>{await s.cancelarAvisos();let liberar;let inicio;const started=new Promise(r=>inicio=r);const pendiente=new Promise(r=>liberar=r);x.gate={then:(...args)=>{inicio();return pendiente.then(...args)}};const tarea=s.actualizarAvisos('A',datos,p);await started;x.auth.currentUser={uid:'B'};const cancel=s.cancelarAvisos();liberar();await tarea;await cancel;assert.equal(x.items.length,0);x.gate=null;});
test('cerrar sesión limpia programación y avisos presentados',async()=>{s.iniciarAvisos();x.auth.currentUser={uid:'A'};await s.actualizarAvisos('A',datos,p);x.auth.currentUser=null;x.observador(null);await s.cancelarAvisos();assert.equal(x.items.length,0);});
