/** Regresiones de integración: persistencia de apertura, texto nativo y configuración. */
import {test,after} from 'node:test';import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,rmSync,readdirSync} from 'node:fs';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createRequire} from 'node:module';import ts from 'typescript';
const req=createRequire(import.meta.url);const temp=mkdtempSync(join(tmpdir(),'frescapp-integracion-'));after(()=>rmSync(temp,{recursive:true,force:true}));
writeFileSync(join(temp,'modelo.cjs'),ts.transpileModule(readFileSync(new URL('../services/inventarioModelo.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText);
const {normalizarProducto}=req(join(temp,'modelo.cjs'));
test('la apertura sobrevive la lectura compartida por Android, web y hogar',()=>{const p=normalizarProducto({nombre:'Leche',cantidad:2,abiertoEn:'2026-10-04'},'v5:leche');assert.equal(p.abiertoEn,'2026-10-04');assert.equal(p.cantidad,2);assert.equal(normalizarProducto({abiertoEn:''},'v5:leche').abiertoEn,'');assert.equal(normalizarProducto({},'v4:antiguo').abiertoEn,undefined);});
function textosFueraDeText(codigo,archivo){const ast=ts.createSourceFile(archivo,codigo,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);const fallos=[];const walk=n=>{if(ts.isJsxText(n)){let p=n.parent;while(p && ts.isJsxFragment(p))p=p.parent;const texto=n.text.includes('\n')?n.text.trim():n.text;if(texto && p && ts.isJsxElement(p) && p.openingElement.tagName.getText(ast)!=='Text'){const l=ast.getLineAndCharacterOfPosition(n.pos);fallos.push(`${archivo}:${l.line+1} ${JSON.stringify(n.text)}`);}}ts.forEachChild(n,walk);};walk(ast);return fallos;}
test('el control detecta incluso el espacio suelto que falla en Android',()=>{assert.equal(textosFueraDeText('<View>{a && <Aviso/>} {b && <Aviso/>}</View>','caso.tsx').length,1);assert.equal(textosFueraDeText('<View><Text>Contenido válido</Text></View>','caso.tsx').length,0);});
test('pantallas nativas no contienen texto JSX fuera de Text',()=>{const fallos=[];const scan=dir=>{for(const d of readdirSync(dir,{withFileTypes:true})){const p=join(dir,d.name);if(d.isDirectory())scan(p);else if(p.endsWith('.tsx')&&!p.endsWith('.web.tsx'))fallos.push(...textosFueraDeText(readFileSync(p,'utf8'),p));}};scan(fileURLToPath(new URL('../components/mobile',import.meta.url)));scan(fileURLToPath(new URL('../app',import.meta.url)));assert.deepEqual(fallos,[]);});
test('el índice usado para cerrar hogares está incluido en el despliegue',()=>{const config=JSON.parse(readFileSync(new URL('../firebase.json',import.meta.url),'utf8'));assert.equal(config.firestore.indexes,'firestore.indexes.json');const indices=JSON.parse(readFileSync(new URL('../'+config.firestore.indexes,import.meta.url),'utf8'));assert(indices.fieldOverrides.some(i=>i.collectionGroup==='hogares'&&i.fieldPath==='hogarId'&&i.indexes.some(x=>x.queryScope==='COLLECTION_GROUP')));});

test('cantidad histórica ausente conserva valor inicial; cero o inválida no inventa existencias',()=>{assert.equal(normalizarProducto({},'v4:a').cantidad,1);for(const cantidad of [0,-1,NaN,Infinity])assert.equal(normalizarProducto({cantidad},'v5:a').cantidad,0);});
