import {test,after} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,writeFileSync,mkdirSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {createRequire} from 'node:module';
const req=createRequire(import.meta.url);const ts=req('typescript');const temp=mkdtempSync(join(tmpdir(),'frescapp-recetas-'));after(()=>rmSync(temp,{recursive:true,force:true}));
for(const f of ['data/recetas','services/recetasModelo','services/fechas']){const p=join(temp,f+'.js');mkdirSync(dirname(p),{recursive:true});writeFileSync(p,ts.transpileModule(readFileSync(new URL('../'+f+'.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText);}
const {RECETAS,INGREDIENTES}=req(join(temp,'data/recetas.js'));const {sugerirRecetas,esIngrediente}=req(join(temp,'services/recetasModelo.js'));const now=new Date(2026,9,4,12);const lote=(nombre,vencimiento='Sin fecha',extra={})=>({id:nombre,codigoBarras:'7801234567890',nombre,marca:'Prueba',categoria:'Otros',cantidad:1,unidad:'unidad',vencimiento,fechaRegistro:'2026-10-04',...extra});
const idea=(nombre,rows)=>sugerirRecetas(rows,now).find(x=>x.receta.id===nombre);
test('dataset consistente con 12 IDs únicos y cantidades válidas',()=>{assert.equal(RECETAS.length,12);assert.equal(new Set(RECETAS.map(r=>r.id)).size,12);for(const r of RECETAS){assert(r.pasos.length>=3);assert.equal(new Set(r.ingredientes.map(i=>i.id)).size,r.ingredientes.length);for(const i of r.ingredientes){assert(Object.hasOwn(INGREDIENTES,i.id));assert(i.cantidad>0 && i.cantidad<=999);}}});
test('reconoce nombres con tildes y distintas marcas',()=>{assert(esIngrediente('Fideos Carozzi espirales','fideos'));assert(esIngrediente('Maíz congelado','choclo'));assert(esIngrediente('Colun Leche de vaca entera','leche'));assert(esIngrediente('Soprole Queso gauda','queso'));});
test('no confunde productos compuestos, harinas o subcadenas',()=>{for(const [n,id] of [['Galletas de arroz','arroz'],['Bebida de arroz','arroz'],['Arroz con leche','arroz'],['Fideos instantáneos','fideos'],['Salsa de tomate','tomate'],['Harina de garbanzo','garbanzos'],['Leche condensada','leche'],['Leche en polvo','leche'],['Leche de almendra','leche'],['Maizena','choclo'],['Fideos de arroz','arroz'],['Porotos verdes','porotos'],['Zapallo italiano','zapallo']])assert.equal(esIngrediente(n,id),false,n);});
test('vencidos, fechas inválidas y cantidades cero no satisfacen ingredientes',()=>{const r=idea('pure-papas',[lote('Papas','03/10/2026'),lote('Papas','31/02/2026'),lote('Papas','Sin fecha',{cantidad:0}),lote('Leche','04/10/2026')]);assert.deepEqual(r.faltantes.map(a=>a.id),['papa']);assert.equal(r.urgentes,1);});
test('sin fecha cuenta como presencia pero no como urgencia',()=>{const r=idea('pure-papas',[lote('Papas'),lote('Leche')]);assert.equal(r.faltantes.length,0);assert.equal(r.urgentes,0);assert.equal(r.sinFecha,2);});
test('repetir lotes no aumenta ingredientes disponibles y prioriza fecha cercana',()=>{const r=idea('pure-papas',[lote('Papas','10/10/2026'),lote('Papas','04/10/2026'),lote('Leche')]);assert.equal(r.disponibles.length,2);assert.equal(r.urgentes,1);assert.equal(r.disponibles.find(a=>a.id==='papa').lotes[0].vencimiento,'04/10/2026');});
test('prioriza recetas que usan fechas próximas antes de cobertura',()=>{const rows=[lote('Tomates','04/10/2026'),lote('Papas'),lote('Leche')];const r=sugerirRecetas(rows,now);assert(r[0].urgentes>0);assert(r.findIndex(x=>x.receta.id==='pure-papas')>0);});
test('no cambia ni descuenta el inventario original',()=>{const rows=[lote('Papas'),lote('Leche')];const antes=JSON.stringify(rows);sugerirRecetas(rows,now);assert.equal(JSON.stringify(rows),antes);});
test('identidad del alimento no se infiere por marca o categoría',()=>{const r=idea('pure-papas',[lote('Producto desconocido','Sin fecha',{marca:'Leche',categoria:'Lácteos'})]);assert.equal(r.disponibles.length,0);});
