import {test,before,beforeEach,after} from 'node:test';import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,rmSync,symlinkSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname,resolve} from 'node:path';import ts from 'typescript';
import {initializeTestEnvironment} from '@firebase/rules-unit-testing';import {doc,setDoc,updateDoc,getDocs,collection,serverTimestamp} from 'firebase/firestore';
const temp=mkdtempSync(join(tmpdir(),'frescapp-recetas-compra-'));symlinkSync(resolve('node_modules'),join(temp,'node_modules'));
for(const f of ['services/recetasCompras.ts','services/recetasModelo.ts','services/comprasModelo.ts','services/fechas.ts','data/recetas.ts','security/identidadProducto.ts','security/validation.ts']){const out=join(temp,f.replace(/\.ts$/,'.js'));mkdirSync(dirname(out),{recursive:true});writeFileSync(out,ts.transpileModule(readFileSync(new URL('../'+f,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from (['"])(\.{1,2}\/[^'"]+)\1/g,(_,q,r)=>`from ${q}${r}.js${q}`));}
writeFileSync(join(temp,'package.json'),'{"type":"module"}');writeFileSync(join(temp,'firebase.js'),'export let db;export function testSetDb(d){db=d;}');writeFileSync(join(temp,'services/auth.js'),'export const auth={get currentUser(){return {uid:globalThis.__UID__}}};export const obtenerUidActual=()=>globalThis.__UID__;');
const {testSetDb}=await import(join(temp,'firebase.js'));const {agregarIngredienteACompras}=await import(join(temp,'services/recetasCompras.js'));let env;let db;
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-frescapp-security',firestore:{rules:readFileSync(new URL('../firestore.rules',import.meta.url),'utf8')}});});
beforeEach(async()=>{await env.clearFirestore();globalThis.__UID__='A';db=env.authenticatedContext('A',{firebase:{sign_in_provider:'password'}}).firestore();testSetDb(db);});
after(async()=>{await env.cleanup();rmSync(temp,{recursive:true,force:true});delete globalThis.__UID__;});
test('reintento y dos acciones simultáneas crean una sola compra',async()=>{const r=await Promise.all([agregarIngredienteACompras('arroz','150','g'),agregarIngredienteACompras('arroz','150','g')]);assert(r.includes('agregado'));assert.equal(await agregarIngredienteACompras('arroz','200','g'),'pendiente');const lista=await getDocs(collection(db,'usuarios/A/listaCompras'));assert.equal(lista.size,1);assert.equal(lista.docs[0].data().cantidad,150);});
test('detecta compra manual compatible y conserva su cantidad',async()=>{await setDoc(doc(db,'usuarios/A/listaCompras/manual'),{nombre:'Arroz integral',cantidad:2,unidad:'kg',comprado:false,creadoEn:serverTimestamp(),actualizadoEn:serverTimestamp()});assert.equal(await agregarIngredienteACompras('arroz','150','g'),'pendiente');assert.equal((await getDocs(collection(db,'usuarios/A/listaCompras'))).size,1);});
test('ingrediente marcado comprado no se agrega nuevamente',async()=>{await setDoc(doc(db,'usuarios/A/listaCompras/manual'),{nombre:'Leche entera',cantidad:1,unidad:'L',comprado:false,creadoEn:serverTimestamp(),actualizadoEn:serverTimestamp()});await updateDoc(doc(db,'usuarios/A/listaCompras/manual'),{comprado:true,actualizadoEn:serverTimestamp()});assert.equal(await agregarIngredienteACompras('leche','0.15','L'),'comprado');assert.equal((await getDocs(collection(db,'usuarios/A/listaCompras'))).size,1);});
test('otra cuenta tiene su lista independiente y cantidad inválida no escribe',async()=>{await agregarIngredienteACompras('arroz','150','g');globalThis.__UID__='B';testSetDb(env.authenticatedContext('B',{firebase:{sign_in_provider:'password'}}).firestore());assert.equal(await agregarIngredienteACompras('arroz','150','g'),'agregado');await assert.rejects(agregarIngredienteACompras('huevo','1.5','unidad'));assert.equal((await getDocs(collection(db,'usuarios/A/listaCompras'))).size,1);});
