import {useState} from 'react';
import {Platform,ScrollView,Text,TextInput,View} from 'react-native';
import {useRouter} from 'expo-router';
import {buscarProductoPorCodigo,type ProductoCatalogo} from '../../services/productos';
import {ALIMENTOS_SIN_CODIGO,alimentoGenerico,UBICACIONES,UNIDADES_GRANEL} from '../../security/identidadProducto';
import {useCompraMultiple} from './CompraMultiple';
import {useTemaApp} from './TemaApp';
import {Aviso,BotonApp,Chip,Confirmacion,Encabezado,ui} from './UI';
export function RegistroComprasPantalla() {
 const c=useCompraMultiple();const {colores}=useTemaApp();const router=useRouter();const [codigo,setCodigo]=useState('');const [buscar,setBuscar]=useState(false);const [error,setError]=useState('');const [producto,setProducto]=useState<ProductoCatalogo|null>(null);const [cantidad,setCantidad]=useState('1');const [fecha,setFecha]=useState('');const [sinFecha,setSinFecha]=useState(false);const [ubicacion,setUbicacion]=useState<'Despensa'|'Refrigerador'|'Congelador'>('Despensa');const [fruta,setFruta]=useState('');const [terminar,setTerminar]=useState(false);
 const bloqueado=c.iniciado || c.ocupado || buscar;const pendientes=c.items.length-c.confirmados.length;
 const campo={color:colores.texto,borderColor:colores.borde,borderWidth:1,borderRadius:12,minHeight:48,padding:12,backgroundColor:colores.tarjeta};
 function elegir(p:ProductoCatalogo){setProducto(p);setCantidad('1');setFecha('');setSinFecha(p.codigoBarras.startsWith('sin:'));setError('');}
 async function consultar(){if(buscar || bloqueado)return;setBuscar(true);setError('');try{const p=await buscarProductoPorCodigo(codigo);if(!p)throw new Error('Código no encontrado. Registra el producto primero desde Agregar en Android.');elegir(p);}catch(e){setError(e instanceof Error && !('code' in e)?e.message:'No pudimos consultar el catálogo. Revisa la conexión.');}finally{setBuscar(false);}}
 return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={ui.contenido}><Encabezado titulo="Registrar una compra" detalle="Prepara hasta 20 registros con su cantidad y fecha; guárdalos cuando termines."/>
 <Aviso texto="Este borrador vive solo mientras tu sesión está abierta. Los productos todavía no están en la despensa hasta pulsar Guardar compra. Revisa cada vencimiento del envase."/>
 {Platform.OS!=='web' && <BotonApp texto="Escanear para esta compra" deshabilitado={bloqueado || c.items.length>=20} onPress={()=>router.push({pathname:'/camara',params:{compra:'1'}})}/>}
 {!c.iniciado && <><TextInput accessibilityLabel="Código para la compra" value={codigo} onChangeText={setCodigo} maxLength={14} keyboardType="number-pad" placeholder="Código de barras" placeholderTextColor={colores.secundario} style={campo}/><BotonApp texto="Buscar código para compra" ocupado={buscar} deshabilitado={c.ocupado} secundario onPress={()=>{void consultar();}}/><TextInput accessibilityLabel="Buscar fruta o verdura para compra" value={fruta} onChangeText={setFruta} placeholder="Fruta o verdura sin código" placeholderTextColor={colores.secundario} style={campo}/>{!!fruta.trim() && <View style={[ui.fila,{flexWrap:'wrap'}]}>{ALIMENTOS_SIN_CODIGO.filter(a=>a[1].toLocaleLowerCase('es').includes(fruta.trim().toLocaleLowerCase('es'))).slice(0,8).map(a=><Chip key={a[0]} texto={a[1]} elegido={producto?.codigoBarras===`sin:${a[0]}`} onPress={()=>{if(!buscar)elegir(alimentoGenerico(`sin:${a[0]}`));}}/>)}</View>}
 {producto && c.items.some(e=>e.producto.codigoBarras===producto.codigoBarras) && <Aviso texto="Ya preparaste este producto. Revisa cantidades y fechas antes de añadir otro lote."/>}{producto && <View style={{gap:12,padding:16,borderWidth:1,borderColor:colores.borde,borderRadius:16}}><Text style={{color:colores.texto,fontWeight:'700',fontSize:20}}>{producto.nombre} · {producto.marca} · {producto.formato}</Text><TextInput accessibilityLabel="Cantidad del producto en compra" value={cantidad} onChangeText={setCantidad} maxLength={8} keyboardType="decimal-pad" style={campo}/>{producto.codigoBarras.startsWith('sin:') && <View style={[ui.fila,{flexWrap:'wrap'}]}>{UNIDADES_GRANEL.map(u=><Chip key={u} texto={u} elegido={producto.unidad===u} onPress={()=>setProducto(alimentoGenerico(producto.codigoBarras,u))}/>)}</View>}<View style={[ui.fila,{flexWrap:'wrap'}]}>{UBICACIONES.map(u=><Chip key={u} texto={u} elegido={ubicacion===u} onPress={()=>setUbicacion(u)}/>)}</View><View style={ui.fila}>{['Con fecha','Sin fecha'].map(t=><Chip key={t} texto={t} elegido={(t==='Sin fecha')===sinFecha} onPress={()=>setSinFecha(t==='Sin fecha')}/>)}</View>{!sinFecha && <TextInput accessibilityLabel="Vencimiento del producto en compra" value={fecha} onChangeText={setFecha} placeholder="DD/MM/AAAA o MM/AAAA" placeholderTextColor={colores.secundario} maxLength={10} style={campo}/>}<BotonApp texto="Añadir producto al borrador" deshabilitado={bloqueado || c.items.length>=20} onPress={()=>{try{if(!/^\d+(?:[.,]\d{1,3})?$/.test(cantidad.trim()))throw new Error('Escribe una cantidad válida.');c.agregar({...producto,cantidad:Number(cantidad.replace(',','.')),vencimiento:sinFecha?'Sin fecha':fecha,ubicacion});setProducto(null);setError('');}catch(e){setError(e instanceof Error?e.message:'Revisa el producto.');}}}/></View>}</>}
 {(error || c.error) && <Aviso texto={error || c.error} error/>}
 <Text style={{color:colores.texto,fontSize:18,fontWeight:'700'}}>{c.items.length} registros · {c.confirmados.length} guardados · {pendientes} pendientes</Text>
 {c.items.map(e=><View key={e.id} style={{padding:16,borderRadius:16,borderWidth:1,borderColor:colores.borde,backgroundColor:colores.tarjeta,gap:8}}><Text style={{color:colores.texto,fontWeight:'700'}}>{e.producto.nombre} · {e.producto.marca}</Text><Text style={{color:colores.secundario}}>{e.producto.cantidad} {e.producto.codigoBarras.startsWith('sin:')?e.producto.unidad:'envases'} · {e.producto.vencimiento} · {e.producto.ubicacion}</Text><Text style={{color:colores.verde}}>{c.confirmados.includes(e.id)?'Guardado':'Pendiente'}</Text>{!c.iniciado && <BotonApp texto={`Quitar del borrador: ${e.producto.nombre}`} secundario onPress={()=>c.quitar(e.id)}/>}</View>)}
 {!!c.items.length && <BotonApp texto={c.iniciado?'Reintentar pendientes':'Guardar compra'} ocupado={c.ocupado} deshabilitado={!pendientes || buscar} onPress={()=>{void c.guardar();}}/>}
 {c.iniciado && <Aviso texto="El borrador queda bloqueado durante el guardado. Reintentar conserva lo ya guardado; para corregir pendientes termina el borrador y prepara una nueva compra."/>}
 {!!c.items.length && <BotonApp texto="Terminar este borrador" secundario deshabilitado={c.ocupado} onPress={()=>setTerminar(true)}/>}
 <Confirmacion visible={terminar} titulo="¿Terminar el borrador?" detalle={`${pendientes} registros pendientes se descartarán del borrador. Los guardados se conservan en tu despensa.`} ocupado={c.ocupado} error="" textoConfirmar="Terminar" confirmar={()=>{c.terminar();setProducto(null);setError('');setTerminar(false);}} cerrar={()=>setTerminar(false)}/>
 </ScrollView>;
}
